### ISSUE TITLE
Issues with login

### ISSUE THREAD

**Issue by gsouf** [apifytech/apify-cli#1]
Hi

I just run the command ``apify login`` and here is the output of the command:

```
Error: Logging into Apify failed, token or userId is not correct.
Success: Logged into Apify!
```

In the end I'm apparently not logged. I dont think it's an issue with wrong credentials, tought, I can try again.

Here is the results when I run the command ``apify push``:

```
Error: You aren't logged call "apify login" to process login.
Info: Push act-name to Apify.
Run: Zipping all act files ...
Error: Cannot read property 'keyValueStores' of undefined
```

**Comment by gsouf** [comment]
It was actually issue with credentials. Was using regular login/password. I was fooled by the double message.

**Comment by drobnikj** [comment]
Hi @gsouf,

thanks for the report!

As you said, you can login only with user id and token, which you can find on https://my.apify.com/account#/integrations .

Anyway, apify-cli is still in development. 
But we release it soon! 💪 

You can use it now if you find some bugs let us know here.

**Comment by gsouf** [comment]
Hi @drobnikj 

Thanks for the answer, I think that this issue can remain open, because as you see when authentication fails there are 2 messages: 

- Login failed
- You are logged successfully

**Comment by drobnikj** [comment]
Hi @gsouf,

I little miss your comment in closed issue, but anyway it should work now. Do you have still this issues?
