### ISSUE TITLE
Cli should generate .idea in .gitignore

### ISSUE THREAD

**Issue by petrpatek** [apifytech/apify-cli#101]
It would be nice to have .idea in default `.gitIgnore` file. I think that I am not the only one that uses idea editors.

**Comment by jancurn** [comment]
IMHO you can commit this directly to develop, it's probably faster than writing the issue here :)

**Comment by drobnikj** [comment]
https://github.com/apifytech/apify-cli/commit/7149d59be7ae62416fb56ba5258121436a0428a4
