### ISSUE TITLE
Improve the templates to be more descriptive

### ISSUE THREAD

**Issue by jancurn** [apifytech/apify-cli#109]
The templates could use more comments, links, and description, to help new users get started faster with Apify. For inspiration how to do this, see the new files in https://github.com/apifytech/actor-quick-start

Also, the Dockerfiles should use `CMD` instruction, rather than rely on the default. It's obscure for users.

**Comment by jancurn** [comment]
Also, we're missing a template for INPUT_SCHEMA.json, let's just add the quick start actor to templates to cover this too.

**Comment by jancurn** [comment]
BTW we should need to use the same default Dockerfile as on the platform, which has 

```
# Optionally, specify how to launch the source code of your actor.
# By default, Apify's base Docker images define the CMD instruction
# that runs the Node.js source code using the command specified
# in the "scripts.start" section of the package.json file.
# In short, the instruction looks something like this:
#
# CMD npm start
```

Otherwise, it fails when people switch to XVFB image.

**Comment by jancurn** [comment]
Related to https://github.com/apifytech/apify-cli/issues/23

**Comment by drobnikj** [comment]
Changes made into in https://github.com/apifytech/actor-templates/pull/6
