### ISSUE TITLE
Templates should use the internal log util instead of pure console.(log, error, ...)

### ISSUE THREAD

**Issue by petrpatek** [apifytech/apify-cli#111]
I think that we should use our log utility instead of console.log inside the node context. What do you think guys?

**Comment by drobnikj** [comment]
It makes sense to use logs function from utils.

**Comment by jancurn** [comment]
Related to https://github.com/apifytech/apify-cli/issues/23

**Comment by drobnikj** [comment]
Moved to https://github.com/apifytech/actor-templates/issues/4
