### ISSUE TITLE
Always use latest SDK in templates

### ISSUE THREAD

**Issue by mnmkng** [apifytech/apify-cli#120]
We should just pull the latest version of SDK using 
```
npm show apify@latest version
``` 
and inject it into the template. Many issues coming from not having the latest SDK.

**Comment by jancurn** [comment]
And also keep them up-to-date, to avoid seeing things like this:

```
WARNING: CheerioCrawler: The "html" parameter of handlePageFunction is deprecated, use "body" instead.
```

**Comment by jancurn** [comment]
Related to https://github.com/apifytech/apify-cli/issues/23

**Comment by drobnikj** [comment]
We moved templates to separate repo, so we easily update Apify SDK version without releasing new cli version.
I added dependabot to check the version in new repo.
