### ISSUE TITLE
error on creating a new project

### ISSUE THREAD

**Issue by andrey82** [apifytech/apify-cli#121]
I have the following error when trying to create a new project :

`root@u1:/code# apify create test

Error: ETXTBSY: text file is busy, rename '/code/test/package.json.1485932518' -> '/code/test/package.json'
`
I rename the file, as instructed, then when trying to run the project, I get 

`root@u1:/code/test# apify run
Warning: You are not logged in with your Apify Account. Some features like Apify Proxy will not work. Call "apify login" to fix that.
Run: npm start

> test@0.0.1 start /code/test
> node main.js

internal/modules/cjs/loader.js:716
    throw err;
    ^

Error: Cannot find module 'apify'
Require stack:
- /code/test/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:713:15)
    at Function.Module._load (internal/modules/cjs/loader.js:618:27)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/code/test/main.js:6:15)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:931:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/code/test/main.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test@0.0.1 start: `node main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-08-22T20_57_06_583Z-debug.log
Error: npm exited with code 1
root@u1:/code/test#
`
More context:
I am runing ubuntu 18 lts
node.js v12.8.1
npm 6.11.2
apify-cli/0.3.11 linux-x64 node-v12.8.1
apify WAS not created in my test directory; there is no node-modules directory !

I have tried instaling apify globaly :
npm install apify -g --unsafe-perm=true --allow-root
> i get
 + apify@0.15.5
updated 1 package in 12.691s

I have the same result when trying apify run

I have also tried instaling localy in my test directory, and i get the following :
`root@u1:/code/test# npm install apify --save --unsafe-perm=true --allow-root
npm WARN test@0.0.1 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: isarray@1.0.0 (node_modules/concat-stream/node_modules/isarray):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, open '/code/test/node_modules/concat-stream/node_modules/isarray/package.json.1282354657'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: safe-buffer@5.1.2 (node_modules/concat-stream/node_modules/safe-buffer):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, open '/code/test/node_modules/concat-stream/node_modules/safe-buffer/package.json.2164404816'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: string_decoder@1.1.1 (node_modules/concat-stream/node_modules/string_decoder):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, open '/code/test/node_modules/concat-stream/node_modules/string_decoder/package.json.3191139421'

npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /code/test/node_modules/body-parser/node_modules/inherits/package.json.2189798571
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/code/test/node_modules/body-parser/node_modules/inherits/package.json.2189798571'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-08-22T21_06_08_072Z-debug.log
`

This is getting extremly frustrating because I had it running just fine a few days before.
The changes I have made to the node ecosystem is that I have instaled mysql with the -g flag. I can not imegine nor find out what the hell I messed up.

Please advise what to try next.

**Comment by andrey82** [comment]
some more context
i was trying to run the create command in an virtualbox shared folder
this is a local dev vm, so I realy do no care about security
the shared folder is mounted automaticaly with the following permissins :
770 owner root [rwx]   group vboxsf [rwx]  an others [---]

in other folders where it does run ok, others can read and execute, and the group is root.

In order to function as it should in the shared folder I need to changes some user's permission.

Does anyone know what user should I add to the vboxsf group ?

Under what user does nodejs run by default ?

**Comment by drobnikj** [comment]
I'm not sure about this issue. But it looks it is connected with npm.

Can you try to npm `uninstall apify-cli -g` and install it again?

**Comment by andrey82** [comment]
Sorry for the late feedback.
The problem came from the fact that I was using a shared folder between windows and my vm as my home folder for the project.
The issue is in fact related to this, it looks like you can not have symlinks in this kind of a setup.
Sorry for the somewhat irrelevant issue.

**Comment by drobnikj** [comment]
We have more issue on a win like that. 
#124 
I don't know how to solve it.
