### ISSUE TITLE
By default act continues in requestQueue if the queue is not deleted manually

### ISSUE THREAD

**Issue by VaclavRut** [apifytech/apify-cli#14]
When I run the act once, it creates a requestQueue, it fails on something, so I update the code and run it once more but it continues in the queue and might crash because of the updates.

I would suggest adding some param for Apify run, maybe something like `apify run -c /  -clean` that would delete the folder of request-queues before the run, because it is also good to have the possibility to continue in the queue.

**Comment by drobnikj** [comment]
It is painful to delete queue after each run, but sometimes you want to keep it.
It also connected with datasets, because items from dataset also stay in the folder.

@VaclavRut suggest: `apify run -c / --clean` - which deletes datasets and queue first and after run act

Let discuss this feature here @mtrunkat @jancurn.

**Comment by jancurn** [comment]
How about calling it `--purge-queues` and `--purge-datasets` instead? Otherwise it's not clear what is deleted, e.g. are key-value stores deleted too?

**Comment by drobnikj** [comment]
Workaround: `rm -rf apify_local/request-queues/default/handled && rm -rf apify_local/request-queues/default/pending && apify run`

It deletes old queue and then run act

**Comment by juansgaitan** [comment]
`apify run; rm -rf apify_local/request-queues/default/pending` to delete the pending requests and prevent the job to continue with the execution after finished.

**Comment by drobnikj** [comment]
Fixed in v0.1.12, you can use -p, --purge, --purge-dataset, --purge-key-value-store, --purge-queue options to clear local stores.
