### ISSUE TITLE
Pushing an actor using its ID with no username produces an error

### ISSUE THREAD

**Issue by jancurn** [apifytech/apify-cli#171]
It seems pushing an actor using its ID if user doesn't have username set can produce this error:

```
> apify push [SOME_ID]
Error: Invalid value provided in undefined: Value must be of type String
```

See https://app.intercom.com/a/apps/kod1r788/inbox/inbox/conversation/26911773569

**Comment by drobnikj** [comment]
It was fixed in https://github.com/apifytech/apify-cli/blob/master/CHANGELOG.md#037--2019-03-18.
The user just used old version of CLI.
