### ISSUE TITLE
apify run execute main.js by default

### ISSUE THREAD

**Issue by drobnikj** [apifytech/apify-cli#5]
For command `apify run` it runs by default main.js file.

User should have option how to override it.

**Comment by mtrunkat** [comment]
It should run `main` file from package.json so user can override it there.

So `package.json` should contain by default:

```javascript
{ 
   ...
   "main": "main.js"
  ...
}

**Comment by jancurn** [comment]
I think `apify run` should only work if there is `apify.json` file. If it's not there, the command should emit an error saying the user needs to run `apify init` first. It's more transparent behavior.

**Comment by jancurn** [comment]
Actually I ran again into this issue now :-/

**Comment by drobnikj** [comment]
It was fixed in v0.1.12. It shows a warning if apify.json doesn't exist.
