### ISSUE TITLE
"apify create" must ensure that project uses the latest version of apify package

### ISSUE THREAD

**Issue by jancurn** [apifytech/apify-cli#55]
The release schedule of `apify-cli` is much slower than of `apify` NPM package, but we need to make sure new projects always use the latest version. We need to run `npm update apify` in the new projects.

**Comment by jancurn** [comment]
Once this is done, we can remove the "Have you checked the code templates..." prompt from publish.sh

**Comment by drobnikj** [comment]
@jancurn We call npm instal with apify create command. So new project'll be with new latest version of apify-js except we changed major version in apify-js. Then we have to update package.json manually to new major version.
I think we do not need call npm update in this case.

**Comment by jancurn** [comment]
The problem is that we upgrade major version quite often, but we don't update CLI often. Then apify package will be outdated for new users, which is not good. How about removing "apify" from deps and only adding "npm install apify --save" to "apify create"?

**Comment by drobnikj** [comment]
But we have to keep in mind, that we can break apify-cli or templates with any incompatible changes.. (e.g. changing some env vars names)

**Comment by jancurn** [comment]
Ok, let's leave it like this then, there's a reminder in `./publish.sh` at least
