### ISSUE TITLE
Act id for apify push

### ISSUE THREAD

**Issue by gsouf** [apifytech/apify-cli#85]
Hi,

With previous version of api cli we could specify the actId directly in apify.json, now we have to specify it on command line, any reason for that?

Can we re-add the ability to specify it in the config file? It's really straighforward when we dont have to remember and specify the id everytime we push!

**Comment by drobnikj** [comment]
Hi @gsouf,

we make apify.json simpler so you should set up just actor name in package.json and we create actor ID from username and actor name when CLI pushes the actor. If there is no actor with this name on the account we create it.

I think you need just use right actor name and you will have the same functionality as with actorId.

**Comment by gsouf** [comment]
@drobnikj if I dont specify any id, it will say that the actor with the given name already exists.

**Comment by drobnikj** [comment]
@gsouf 
It is strange, can you send me which version of apify-cli are you using?
`apify --version`

I'll check it.

**Comment by gsouf** [comment]
```
$ apify --version
(node:14128) Error Plugin: apify-cli: files attribute must be specified in /usr/local/lib/node_modules/apify-cli/package.json
module: @oclif/config@1.9.0
plugin: apify-cli
root: /usr/local/lib/node_modules/apify-cli
See more details with DEBUG=*
apify-cli/0.3.3 linux-x64 node-v8.10.0
```

**Comment by drobnikj** [comment]
This is a strange error. It works on macOS, I just tested it. Can you try to uninstall and install apify-cli again?

`npm uninstall apify-cli -g && npm install apify-cli -g`

We tested CLI on Linux with node js v8.11 and it works.

If reinstall didn't help you can try to update node js to LTS v8 version.

**Comment by gsouf** [comment]
I re-installed apify-cli as you asked and I still have the issue:

```
apify push
(node:9156) Error Plugin: apify-cli: files attribute must be specified in /usr/local/lib/node_modules/apify-cli/package.json
module: @oclif/config@1.9.0
plugin: apify-cli
root: /usr/local/lib/node_modules/apify-cli
See more details with DEBUG=*
Error: Some other actor already has this name ("some actor name").
```

Content of ``apify.json``:

```
{
    "name": "some actor name",
    "version": "0.1",
    "buildTag": "latest",
    "env": null
}
```

**Comment by drobnikj** [comment]
I found the issue, it happens if a user doesn't have a username.
I created the issue for that:
#89

**Comment by drobnikj** [comment]
As workaround before we fix it, the user can set up a username on Apify account.
