### ISSUE TITLE
Env variables from terminal are not propagated to the actor

### ISSUE THREAD

**Issue by jakubbalada** [apifytech/apify-cli#88]
If I run 
`APIFY_ACT_ID=actor apify run`
in a terminal, I've got 
`ReferenceError: APIFY_ACT_ID is not defined`

**Comment by drobnikj** [comment]
You can get the process environment variables from [process.env](https://nodejs.org/api/process.html#process_process_env).

try to get you variable using:
`process.env.APIFY_ACT_ID`

I tested and it works.

**Comment by jakubbalada** [comment]
damn, thanks

**Comment by drobnikj** [comment]
@jakubbalada There is one more way all env vars using by Apify platform are stored in [Apify.getEnv()](https://sdk.apify.com/docs/api/apify#module_Apify.getEnv).
