### ISSUE TITLE
apify init should create apify_storage even when already having apify.json

### ISSUE THREAD

**Issue by metalwarrior665** [apifytech/apify-cli#98]
This makes sense for multiple local environments

**Comment by drobnikj** [comment]
Folder apify_storage should be created with the first usage of apify storage. It doesn't work so it is a bug. But init can create apify_storage in case there is apify.json.

Things to fix:
- [ ] init has to create apify_storage in case there is apify.json
- [ ] apify_storage has to be created with the first use of some apify_storages
